version: '2.1'

services:
  kong-database:
    container_name: kong-database
    image: postgres:9.6.9-alpine
    environment:
      - POSTGRES_USER=kong
      - POSTGRES_DB=kong
    volumes:
      - ./data/postgresql:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 3

  kong:
    container_name: kong
    build: ./kong
    depends_on:
      kong-database:
        condition: service_healthy
    ports:
      - 8000:8000
      - 8001:8001
      - 8443:8443
      - 8444:8444
    environment:
      - KONG_DATABASE=postgres
      - KONG_PG_HOST=kong-database
      - KONG_LOG_LEVEL=debug
      - KONG_PROXY_ACCESS_LOG=/dev/stdout
      - KONG_ADMIN_ACCESS_LOG=/dev/stdout
      - KONG_PROXY_ERROR_LOG=/dev/stderr
      - KONG_ADMIN_ERROR_LOG=/dev/stderr
      - KONG_ADMIN_LISTEN=0.0.0.0:8001
      - KONG_ADMIN_LISTEN_SSL=0.0.0.0:8444
    healthcheck:
      test: ["CMD-SHELL", "nc -z localhost 8001"]
      interval: 10s
      timeout: 5s
      retries: 3
    command: kong start

  kong-dashboard:
    container_name: kong-dashboard
    build: ./kong-dashboard
    depends_on:
      kong:
        condition: service_healthy
    ports:
      - 8080:8080
    command: bin/kong-dashboard.js start --kong-url http://kong:8001

  konga:
    container_name: konga
    build: ./konga
    depends_on:
      kong:
        condition: service_healthy
    ports:
      - 1337:1337
    environment:
      - NODE_ENV=production
    command: app/start.sh
